language: php

matrix:
  include:
  - php : 7.1.3
  - php : 7.2
  fast_finish: true

env:
  global:
    TEST_CONFIG="phpunit.xml.dist"

before_script:
- travis_retry
- cp .env.dist .env
- composer self-update
- composer install --no-scripts

script:
- bin/phpunit

notifications:
  email:
  -  mailer.dev.brice@gmail.com